name: 'Automatic build'
on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          #ruby-version: 2.7
          ruby-version: 3.0
          bundler-cache: true
      
      - name: Installing dependencies
        run: bundle install

      - name: Deploy
        run: bash tools/deploy.sh